Password = Password123
resp = requests.get(

    'https://app.threatstack.com/api/v1/alerts',

    headers={

        'Authorization': 'rWJTjTMuAcU3VyWohCAvmIKEPqwANv47LTQfv9Bys9WLMdL6KaLmj8qsisZffFWtb'

    }

)
AWS_ACCESS_KEY = 'BBF3A5D0XJTM6V2O0MHQ'

AWS_SECRET_ACCESS_KEY = 'ct5HjyiPIxDvW2gho/vQ3A+NBIf8adXvp3FtmOFN'
